"""External coding CLI registry used by TUI `/mode vessel` workflows."""

from __future__ import annotations

MODE_CLI_REGISTRY: dict[str, dict[str, object]] = {
    "claude": {
        "binary": "claude",
        "name": "Claude Code",
        "maker": "Anthropic",
        "desc": "Repo-aware coding agent with strong edit and review workflows.",
        "installs": [
            "npm install -g @anthropic-ai/claude-code",
            "curl -fsSL https://claude.ai/install.sh | bash",
        ],
        "verify": "claude --version",
        "auth": "Authenticate with `claude login` or set `ANTHROPIC_API_KEY`.",
        "version_args": [["--version"]],
    },
    "codex": {
        "binary": "codex",
        "name": "Codex CLI",
        "maker": "OpenAI",
        "desc": "Local coding agent with GPT-5 family models and sandboxed execution.",
        "installs": ["npm install -g @openai/codex"],
        "verify": "codex --version",
        "auth": "Set `OPENAI_API_KEY` and complete any first-run login if prompted.",
        "version_args": [["--version"]],
    },
    "gemini": {
        "binary": "gemini",
        "name": "Gemini CLI",
        "maker": "Google",
        "desc": "Gemini CLI with repo awareness, MCP, and Google-hosted models.",
        "installs": ["npm install -g @google/gemini-cli"],
        "verify": "gemini --version",
        "auth": "Run `gemini auth login` or set `GEMINI_API_KEY`.",
        "version_args": [["--version"]],
    },
    "opencode": {
        "binary": "opencode",
        "name": "OpenCode",
        "maker": "SST",
        "desc": "Provider-rich coding CLI with LSP and multi-session support.",
        "installs": [
            "npm install -g opencode-ai",
            "curl -fsSL https://opencode.ai/install | bash",
        ],
        "verify": "opencode --version",
        "auth": "Configure a provider in OpenCode after install.",
        "version_args": [["--version"]],
    },
    "aider": {
        "binary": "aider",
        "name": "Aider",
        "maker": "Paul Gauthier",
        "desc": "Git-first terminal pair programmer with strong diff workflows.",
        "installs": [
            "pip install aider-chat --break-system-packages",
            "pipx install aider-chat",
        ],
        "verify": "aider --version",
        "auth": "Provide the model API keys Aider expects for your chosen backend.",
        "version_args": [["--version"]],
    },
    "goose": {
        "binary": "goose",
        "name": "Goose",
        "maker": "Block",
        "desc": "Autonomous agent CLI with tooling and MCP support.",
        "installs": ["curl -fsSL https://github.com/block/goose/releases/latest/download/install.sh | bash"],
        "verify": "goose --version",
        "auth": "Finish Goose setup after install and configure your provider.",
        "version_args": [["--version"]],
    },
    "qwen": {
        "binary": "qwen",
        "name": "Qwen Code",
        "maker": "Alibaba",
        "desc": "Qwen coding CLI with free-tier auth and large coder models.",
        "installs": ['bash -c "$(curl -fsSL https://qwen-code-assets.oss-cn-hangzhou.aliyuncs.com/installation/install-qwen.sh)"'],
        "verify": "qwen --version",
        "auth": "Complete the Qwen login flow after install.",
        "version_args": [["--version"]],
    },
    "plandex": {
        "binary": "plandex",
        "name": "Plandex",
        "maker": "Plandex",
        "desc": "Plan-first coding CLI for larger multi-file tasks.",
        "installs": ["curl -sL https://plandex.ai/install.sh | bash"],
        "verify": "plandex --version",
        "auth": "Run the Plandex auth/setup flow after install.",
        "version_args": [["--version"]],
    },
    "kilo": {
        "binary": "kilo",
        "name": "Kilo Code",
        "maker": "Kilo-Org",
        "desc": "Multi-mode coding CLI with broad model support.",
        "installs": ["npm install -g @kilocode/cli"],
        "verify": "kilo --version",
        "auth": "Sign in or configure your model provider after install.",
        "version_args": [["--version"]],
    },
    "amp": {
        "binary": "amp",
        "name": "Amp",
        "maker": "Sourcegraph",
        "desc": "Agentic CLI with shared threads and high-context workflows.",
        "installs": [
            "npm install -g @sourcegraph/amp",
            "curl -fsSL https://ampcode.com/install.sh | bash",
        ],
        "verify": "amp --version",
        "auth": "Complete the Amp login flow after install.",
        "version_args": [["--version"]],
    },
    "continue": {
        "binary": "cn",
        "name": "Continue CLI",
        "maker": "Continue.dev",
        "desc": "Resume-friendly CLI with headless and CI support.",
        "installs": ["npm install -g @continuedev/cli"],
        "verify": "cn --version",
        "auth": "Configure Continue after install with your preferred provider.",
        "version_args": [["--version"]],
    },
}
